export const queryKeys = {
  listKnowledgebases: 'desk_knowledgebases',
  viewKnowledgebase: 'desk_knowledgebase',
  createKnowledgebase: 'desk_createKnowledgebase',
  updateKnowledgeBase: 'desk_updateKnowledgeBase',
  deleteKnowledgebase: 'desk_deleteKnowledgebase',
  createKBInserted: 'desk_createKBInserted',
  deleteKBInserted: 'desk_deleteKBInserted',
  kbInserteds: 'desk_kbInserteds',
  knowledgebase: 'desk_knowledgebase',
  kbCategories: 'desk_kbCategories',
  deleteKBCategory: 'desk_deleteKBCategory',
  sortKBCategory: 'desk_sortKBCategory',
  updateKBCategory: 'desk_updateKBCategory',
  changeKBPublishStatus: 'desk_changeKBPublishStatus',
  changeKBHelpfulStatus: 'desk_changeKBHelpfulStatus',
  cloneKnowledgebase: 'desk_CloneKB',
  tags: 'desk_tags',
  createKBCategory: 'desk_createKBCategory',
  moveKB: 'desk_moveKB',
  updateKBPublishStatus: 'desk_changeKBPublishStatus',
  kbRestore: 'desk_restoreKB',
  kbDeleteRecovery: 'desk_deleteKBRecovery',
  kbEmptyRecovery: 'desk_emptyKBRecovery',
  deskKBComments: `desk_kbComments`,
  deskKBComment: `desk_kbComment`,

  deskCreateKBComment: `desk_createKBComment`,
  deskUpdateKBComment: `desk_updateKBComment`,
  deskDeleteKBComment: `desk_deleteKBComment`
};
