export const queryKeys = {
  viewItem: 'product_item',
  listItem: 'product_items',
  deleteItem: 'product_deleteItem',
  updateItem: 'product_updateItem',
  createItems: 'product_createItems',
  listRelatedVendor: 'product_item',
  listAssignRep: 'product_itemAssignTo',
  createAssignRep: 'product_createItemAssignTo',
  deleteAssignRep: 'product_deleteItemAssignTo',
  changeAssignRep: 'product_changeItemAssignTo',
  nextIdBulk: 'setting_nextIdBulk',
  listTrackingItem: 'site_items',
  listAssociatedItem: 'product_item',
  productRestoreItem: 'product_restoreItem',
  productDeleteItemRecovery: 'product_deleteItemRecovery',
  productEmptyItemRecovery: 'product_emptyItemRecovery',
  updateItemBatch: 'product_updateItemBatch',
};
