export const KEY_NAME_COMPETITOR_ID = 'id';
export const KEY_NAME_COMPETITOR_CODE = 'code';
export const KEY_NAME_COMPETITOR_NAME = 'name';
export const KEY_NAME_COMPETITOR_WEBSITE = 'website';
export const KEY_NAME_COMPETITOR_PRODUCT = 'products';
export const KEY_NAME_COMPETITOR_STRENGTH = 'strength';
export const KEY_NAME_COMPETITOR_WEAKNESS = 'weakness';
export const KEY_NAME_COMPETITOR_DESCRIPTION = 'description';
export const KEY_NAME_COMPETITOR_ORDER_DATE = 'orderDate';
export const KEY_NAME_COMPETITOR_EXPECTED_SHIPMENT_DATE = 'expectedShipmentDate';
export const KEY_NAME_COMPETITOR_SHIPPED_DATE = 'shippedDate';
export const KEY_NAME_COMPETITOR_OPPORTUNITY = 'opportunity'; //TODO: opportunities
export const KEY_NAME_COMPETITOR_CREATED_BY = 'createdBy';
export const KEY_NAME_COMPETITOR_CREATED_AT = 'createdAt';
export const KEY_NAME_COMPETITOR_UPDATED_BY = 'updatedBy';
export const KEY_NAME_COMPETITOR_UPDATED_AT = 'updatedAt';
export const KEY_NAME_COMPETITOR_DELETED_BY = 'deletedBy';
export const KEY_NAME_COMPETITOR_DELETED_AT = 'deletedAt';
