// GraphQL key
export const queryKeys = {
  listActivity: 'activity_activities',
  viewActivity: 'activity_activity',
  createActivity: 'activity_createActivity',
  assignTos: 'activity_assignTos',
  createAssignTo: 'activity_createAssignTo',
  deleteAssignTo: 'activity_deleteAssignTo',
  products: 'activity_products',
  createProduct: 'activity_createProduct',
  deleteProduct: 'activity_deleteProduct',
  tags: 'activity_tags',
  createTag: 'activity_createTag',
  deleteTag: 'activity_deleteTag',
  relatedTos: 'activity_relatedTos',
  createRelatedTo: 'activity_createRelatedTo',
  deleteRelatedTo: 'activity_deleteRelatedTo',
  createTaskChecklist: 'activity_createTaskChecklist',
  updateTaskChecklist: 'activity_updateTaskChecklist',
  deleteTaskChecklist: 'activity_deleteTaskChecklist',
  listChecklist: 'activity_checklist',
  listSequence: 'activity_sequences',
  createTaskSequence: 'activity_createTaskSequence',
  updateTaskSequence: 'activity_updateTaskSequence',
  deleteTaskSequence: 'activity_deleteTaskSequence',
  deleteActivity: 'activity_deleteActivity',
  updateActivity: 'activity_updateActivity',
  listComparisonUser: 'analytic_activityComparisons',
  restoreActivity: 'activity_restoreActivity',
  deleteRecovery: 'activity_deleteRecovery',
  emptyRecovert: 'activity_emptyRecovery'
};
