export const KEY_NAME_QUOTE_ID = 'id';
export const KEY_NAME_QUOTE_CODE = 'code';
export const KEY_NAME_QUOTE_NAME = 'name';
export const KEY_NAME_QUOTE_CUSTOMER = 'customer';
export const KEY_NAME_QUOTE_RECIPIENTS = 'recipients'; //FOR revision
export const KEY_NAME_QUOTE_REVISION_ID = 'revisionCode'; //FOR revision
export const KEY_NAME_QUOTE_CUSTOMER_CATEGORY = 'customerCategory';
export const KEY_NAME_QUOTE_ACCOUNT = 'account'; //UN-USE
export const KEY_NAME_QUOTE_CONTACT = 'contact'; //UN-USE
export const KEY_NAME_QUOTE_SUBJECT = 'subject'; //UN-USE
export const KEY_NAME_QUOTE_OPPORTUNITY = 'opportunity';
export const KEY_NAME_QUOTE_BILL_TO = 'billTo';
export const KEY_NAME_QUOTE_SHIP_TO = 'shipTo';
export const KEY_NAME_QUOTE_DATE = 'quoteDate';
export const KEY_NAME_QUOTE_EXPIRY_DATE = 'expiryDate';
export const KEY_NAME_QUOTE_EXPECTED_SHIPMENT_DATE = 'expectedShipmentDate';
export const KEY_NAME_QUOTE_CLOSED_AT = 'closedAt';
export const KEY_NAME_QUOTE_PROCESS = 'process';
export const KEY_NAME_QUOTE_TEMPLATE = 'quoteTpl';
export const KEY_NAME_QUOTE_EMAI_TEMPLATE = 'emailTpl';
export const KEY_NAME_QUOTE_SALES_REP = 'salesRep';
export const KEY_NAME_QUOTE_DESCRIPTION = 'description';
export const KEY_NAME_QUOTE_PRODUCT = 'product';
export const KEY_NAME_QUOTE_PRODUCT_ITEM = 'productItem';
export const KEY_NAME_QUOTE_ITEMS = 'items';
export const KEY_NAME_QUOTE_SUMMARY = 'summary';
export const KEY_NAME_QUOTE_TOTAL_AMOUNT = 'totalAmount';
export const KEY_NAME_QUOTE_CURRENCY = 'currency';
export const KEY_NAME_QUOTE_CUSTOMER_NOTE = 'customerNote';
export const KEY_NAME_QUOTE_TERM_CONDITION = 'termCondition';
export const KEY_NAME_QUOTE_TERM_CONDITION_CONTENT = 'termConditionContent';
export const KEY_NAME_QUOTE_FILES = 'files';
export const KEY_NAME_QUOTE_STAGE = 'stage';
export const KEY_NAME_QUOTE_STATUS = 'status';
export const KEY_NAME_QUOTE_CREATED_BY = 'createdBy';
export const KEY_NAME_QUOTE_CREATED_AT = 'createdAt';
export const KEY_NAME_QUOTE_UPDATED_BY = 'updatedBy';
export const KEY_NAME_QUOTE_UPDATED_AT = 'updatedAt';
export const KEY_NAME_QUOTE_DELETED_BY = 'deletedBy';
export const KEY_NAME_QUOTE_DELETED_AT = 'deletedAt';

// hidden field view
export const KEY_NAME_QUOTE_CREATE_INVOICE = 'createInvoice';
export const KEY_NAME_QUOTE_PRICE_LIST = 'priceList';
export const KEY_NAME_QUOTE_PRODUCT_DETAIL = 'productDetail';
