export const queryKeys = {
  listQuote: 'quote_quotes',
  viewQuote: 'quote_quote',
  viewQuoteRevision: 'quote_quoteRevision',
  createQuote: 'quote_createQuote',
  deleteQuote: 'quote_deleteQuote',
  updateQuote: 'quote_updateQuote',
  updateQuoteRevision: 'quote_updateQuoteRevision',
  bulkUpdateQuote: 'quote_bulkUpdateQuote',
  cancelQuote: 'quote_markQuoteAsCancelled',
  copyQuote: 'quote_copyQuote',
  restoreQuote: 'quote_restoreQuote',
  emptyRecoveryQuote: 'quote_emptyRecovery',
  deleteRecoveryQuote: 'quote_deleteRecovery',
  listAssignRep: 'quote_assignTo',
  createAssignRep: 'quote_createAssignTo',
  deleteAssignRep: 'quote_deleteAssignTo',
  changeAssignRep: 'quote_changeAssignTo',
  quoteCreateItem: 'quote_createItem',
  quoteUpdateItem: 'quote_updateItem',
  quoteDeleteItem: 'quote_deleteItem',
  quoteCreateFile: 'quote_createQuoteFile',
  quoteDeleteFile: 'quote_deleteQuoteFile'
};
