export enum EAssignmentRuleModule {
  //SALES = 'AR_MODULE_SALES',
  DESK = 'AR_MODULE_DESK',
  OPPORTUNITY = 'AR_MODULE_OPPORTUNITY'
}

export enum EARAssignToType {
  USERS = 'AR_ASSIGN_TO_TYPE_USERS',
  GROUPS = 'AR_ASSIGN_TO_TYPE_GROUPS'
}

export enum EARAssignToMode {
  OWNER = 'AR_ASSGIN_TO_MODE_OWNER',
  ROUND_ROBIN = 'AR_ASSGIN_TO_MODE_ROUND_ROBIN',
  BALANCE_CAPACITY = 'AR_ASSGIN_TO_BALANCE_CAPACITY'
}
//Ticket Classification

export enum EAssignmentRuleCriteria {
  CHANNEL = 'criteria_channel',
  TAG = 'criteria_tag',
  TICKET_CLASSIFICATION = 'criteria_ticket_classification',
  CATEGORY = 'criteria_category'
}

export enum EAREntryAssignToMode {
  USER = 'AR_ASSGIN_TO_MODE_USER',
  GROUP = 'AR_ASSGIN_TO_MODE_GROUP',
  USERS = 'AR_ASSGIN_TO_MODE_USERS',
  GROUPS = 'AR_ASSGIN_TO_MODE_GROUPS'
}
export enum EAREntryAssignToType {
  NONE = 'AR_ASSIGN_TO_TYPE_NONE',
  QUEUE = 'AR_ASSIGN_TO_TYPE_QUEUE',
  ROUND_ROBIN = 'AR_ASSIGN_TO_TYPE_ROUND_ROBIN',
  BALANCE_NUM = 'AR_ASSIGN_TO_TYPE_LOAD_BALANCE_NUM',
  BALANCE_CAP = 'AR_ASSIGN_TO_TYPE_LOAD_BALANCE_CAP'
}

export enum EAREntryCriteriaType {
  NONE = 'AR_CRITERIA_NONE',
  CUSTOMER = 'AR_CRITERIA_CUSTOMER',
  ATTRIBUTE = 'AR_CRITERIA_ATTRIBUTE',
  TAG = 'AR_CRITERIA_TAG',
  CLASSIFICATION = 'AR_CRITERIA_TICKET_CLASSIFICATION',
  CATEGORY = 'AR_CRITERIA_CATEGORY',
  PRODUCT = 'AR_CRITERIA_PRODUCT',
  EMAIL = 'AR_CRITERIA_EMAIL'
}
