// Desk - assignment User
export const KEY_SETTING_PREFERENCES_ASSIGNMENT_USER_ID = 'id';
export const KEY_SETTING_PREFERENCES_ASSIGNMENT_USER_TYPE = 'type';
export const KEY_SETTING_PREFERENCES_ASSIGNMENT_USER_NAME = 'name';
export const KEY_SETTING_PREFERENCES_ASSIGNMENT_USER_EMAIL = 'email';
export const KEY_SETTING_PREFERENCES_ASSIGNMENT_USER_MOBILE = 'mobile';
export const KEY_SETTING_PREFERENCES_ASSIGNMENT_USER_PHONE = 'phone';
export const KEY_SETTING_PREFERENCES_ASSIGNMENT_USER_ACTIVE = 'active';
export const KEY_SETTING_PREFERENCES_ASSIGNMENT_USER_USER = 'user';
export const KEY_SETTING_PREFERENCES_ASSIGNMENT_USER_IS_EMAIL = 'isEmail';
export const KEY_SETTING_PREFERENCES_ASSIGNMENT_USER_Is_SMS = 'isSms';

// Desk - assignment Group

export const KEY_SETTING_PREFERENCES_ASSIGNMENT_GROUP_ID = 'id';
export const KEY_SETTING_PREFERENCES_ASSIGNMENT_GROUP_NAME = 'name';
export const KEY_SETTING_PREFERENCES_ASSIGNMENT_GROUP_USERS = 'users';
export const KEY_SETTING_PREFERENCES_ASSIGNMENT_GROUP_ACTIVE = 'active';
export const KEY_SETTING_PREFERENCES_ASSIGNMENT_GROUP_DESCRIPTION = 'description';
export const KEY_SETTING_PREFERENCES_ASSIGNMENT_GROUP_TOTAL_REPS = 'totalReps';
export const KEY_SETTING_PREFERENCES_ASSIGNMENT_GROUP_REPS = 'reps';
