import {EChartType, ESectionType, EUserType} from "@analytic/main/types/enum";

export const sectionCustomer: any = {
  [EUserType.USER_TYPE_USER]: [
    EChartType.CHART_CUSTOMER_TREND,
    EChartType.CHART_CUSTOMER_PERIOD,
    EChartType.CHART_CUSTOMER_LAST_UPDATED
  ],
  [EUserType.USER_TYPE_ADMIN]: [
    EChartType.CHART_CUSTOMER_TREND,
    EChartType.CHART_CUSTOMER_RATING,
    EChartType.CHART_CUSTOMER_INDUSTRY
  ]
};

export const sectionActivity: any = {
  [EUserType.USER_TYPE_USER]: [
    EChartType.CHART_ACTIVITY_TREND,
    EChartType.CHART_ACTIVITY_TODO,
    EChartType.CHART_ACTIVITY_REP_PERFORMANCE,
    EChartType.CHART_ACTIVITY_TYPE,
    EChartType.CHART_ACTIVITY_DURATION,
    EChartType.CHART_ACTIVITY_GROUP_DURATION,
    EChartType.CHART_ACTIVITY_GROUP_TOTAL,
    EChartType.CHART_ACTIVITY_COMPARISON
  ],
  [EUserType.USER_TYPE_ADMIN]: [
    EChartType.CHART_ACTIVITY_TREND,
    EChartType.CHART_ACTIVITY_GROUP_PERFORMANCE,
    EChartType.CHART_ACTIVITY_REP_PERFORMANCE,
    EChartType.CHART_ACTIVITY_TOTAL_BY_GROUP,
    EChartType.CHART_ACTIVITY_TOTAL_BY_REP,
    EChartType.CHART_ACTIVITY_TOP_PERFORMER_BY_CALL,
    EChartType.CHART_ACTIVITY_TOP_PERFORMER_BY_TASK,
    EChartType.CHART_ACTIVITY_TOP_PERFORMER_BY_EMAIL,
    EChartType.CHART_ACTIVITY_TOP_PERFORMER_BY_SMS,
    EChartType.CHART_ACTIVITY_PURPOSE,
    EChartType.CHART_ACTIVITY_BY_TYPE,
    EChartType.CHART_ACTIVITY_OVERDUE_REP_CHART,
    EChartType.CHART_ACTIVITY_BY_PRIORITY_CHART,
    EChartType.CHART_ACTIVITY_COMPARISON
  ]
};

export const sectionDesk: any = {
  [EUserType.USER_TYPE_USER]: [
    EChartType.CHART_TICKET_TREND,
    EChartType.CHART_TICKET_PERFORMER_BY_RESOLVE_TIME_EFFICIENCY,
    EChartType.CHART_TICKET_OVERVIEW,
    EChartType.CHART_TICKET_PERFORMER_BY_RESOLVE_TIME,
    EChartType.CHART_TICKET_GROUP_PERFORMANCE,
    EChartType.CHART_TICKET_GROUP_PERFORMANCE_BY_ASSIGNED_TICKET,
    EChartType.CHART_TICKET_GROUP_PERFORMANCE_BY_RESOLVE_TIME_EFFICIENCY,
    EChartType.CHART_TICKET_GROUP_PERFORMANCE_BY_RESOLVED_TICKET,
    EChartType.CHART_TICKET_GROUP_PERFORMANCE_BY_UNRESOLVED_TICKET,
    EChartType.CHART_TICKET_GROUP_PERFORMANCE_BY_RESOLUTION_TIME,
    EChartType.CHART_TICKET_PRIORITY,
    EChartType.CHART_TICKET_TOP_ISSUE,
    EChartType.CHART_KB_REP_PUBLISHED_ARTICLE,
    EChartType.CHART_KB_REP_INSERTED_ARTICLE
  ],
  [EUserType.USER_TYPE_ADMIN]: [
    EChartType.CHART_TICKET_TREND,
    EChartType.CHART_TICKET_BY_CATEGORY,
    EChartType.CHART_TICKET_AVG_SUPPORT_PERFORMER,
    EChartType.CHART_TICKET_OVERVIEW,
    EChartType.CHART_TICKET_GROUP_PERFORMER,
    EChartType.CHART_TICKET_REP_PERFORMER,
    EChartType.CHART_TICKET_TOP_PERFORMER_BY_AVG_RESOLUTION_TIME,
    EChartType.CHART_TICKET_TOP_PERFORMER_BY_RESOLVED_TICKET,
    EChartType.CHART_TICKET_TOP_PERFORMER_BY_RESOLVE_TIME_EFFICIENCY,
    EChartType.CHART_TICKET_TOP_PERFORMER_BY_UNRESOLVED_TICKET,
    EChartType.CHART_TICKET_REP_BY_AVG_RESOLUTION_TIME,
    EChartType.CHART_TICKET_REP_BY_RESOLVED_TICKET,
    EChartType.CHART_TICKET_REP_BY_RESOLVE_TIME_EFFICIENCY,
    EChartType.CHART_TICKET_REP_BY_UNRESOLVED_TICKET,
    EChartType.CHART_TICKET_TOP_GROUP_BY_AVG_RESOLUTION_TIME,
    EChartType.CHART_TICKET_TOP_GROUP_BY_AVG_RESOLUTION_TIME_EFFICIENCY,
    EChartType.CHART_TICKET_TOP_GROUP_BY_AVG_RESOLVED_TICKET,
    EChartType.CHART_TICKET_TOP_GROUP_BY_AVG_UNRESOLVED_TICKET,
    EChartType.CHART_KB_OVERVIEW,
    EChartType.CHART_KB_REP_PUBLISHED_ARTICLE,
    EChartType.CHART_KB_REP_VIEWED_ARTICLE,
    EChartType.CHART_KB_REP_INSERTED_ARTICLE
  ]
};

export const sectionSatisfaction: any = {
  [EUserType.USER_TYPE_USER]: [
    EChartType.CHART_SATISFACTION_AVG_CUSTOMER_SATISFACTION,
    EChartType.CHART_SATISFACTION_QUESTION
  ],
  [EUserType.USER_TYPE_ADMIN]: [
    EChartType.CHART_SATISFACTION_AVG_CUSTOMER_SATISFACTION,
    EChartType.CHART_SATISFACTION_QUESTION
  ]
};

export const sectionSus: any = {
  [EUserType.USER_TYPE_USER]: [
    EChartType.CHART_SUS_ISSUED,
    EChartType.CHART_SUS_MEDIUM,
    EChartType.CHART_SUS_SOURCE,
    EChartType.CHART_SUS_CAMPAIGN,
    EChartType.CHART_SUS_CLICK_TIME
  ],
  [EUserType.USER_TYPE_ADMIN]: [
    EChartType.CHART_SUS_ISSUED,
    EChartType.CHART_SUS_MEDIUM,
    EChartType.CHART_SUS_SOURCE,
    EChartType.CHART_SUS_CAMPAIGN,
    EChartType.CHART_SUS_CLICK_TIME
  ]
};

export const sectionAll: any = {
  [ESectionType.SECTION_CUSTOMER]: sectionCustomer,
  [ESectionType.SECTION_ACTIVITY]: sectionActivity,
  [ESectionType.SECTION_DESK]: sectionDesk,
  [ESectionType.SECTION_SATISFACTION]: sectionSatisfaction,
  [ESectionType.SECTION_SUS]: sectionSus
};

export const sectionTitles: any = {
  [ESectionType.SECTION_CUSTOMER]: 'ncrm_common_customer_analysis',
  [ESectionType.SECTION_ACTIVITY]: 'ncrm_common_customer_activity_analysis',
  [ESectionType.SECTION_DESK]: 'ncrm_common_customer_ticket_analysis',
  [ESectionType.SECTION_SATISFACTION]: 'ncrm_common_customer_satisfaction_analysis',
  [ESectionType.SECTION_SUS]: 'ncrm_common_simple_url_shortener'
};
