export const queryKeys = {
  menuSetting: 'setting_menuSetting',
  updateMenuSetting: 'setting_updateMenuSetting',
  deleteAssignmentUser: 'desk_deleteAssignmentUsers',
  addAssignmentUser: 'desk_createAssignmentUsers',
  updateAssignmentUser: 'desk_updateAssignmentUsers',
  deleteAssignmentReps: 'desk_deleteAssignmentGroupReps',
  addAssignmentReps: 'desk_deleteAssignmentGroupReps',
  updateAssignmentReps: 'desk_updateAssignmentGroupRep',
  deleteAssignmentGroup: 'desk_deleteAssignmentGroup',
  updateAssignmentGroup: 'desk_UpdateAssignmentGroup',
  addAssignmentGroup: 'desk_createAssignmentGroup',
  ticketCategories: 'desk_ticketCategories',
  createTicketCategory: 'desk_createTicketCategory',
  updateTicketCategory: 'desk_updateTicketCategory',
  deleteTicketCategory: 'desk_deleteTicketCategory',
  createTicketCategoryRule: 'desk_createTicketCategoryRule',
  updateTicketCategoryRule: 'desk_updateTicketCategoryRule',
  deleteTicketCategoryRule: 'desk_deleteTicketCategoryRule',
  listProductGroups: 'product_groups',
  addProductGroup: 'product_createGroup',
  updateProductGroup: 'product_updateGroup',
  deleteProductGroup: 'product_deleteGroup'
};
